name: MacOS Setup
on: [push]

jobs:
  setup:
    name: Testing MacOS Setup
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Set Permissions
        run: chmod +x *.sh
        shell: bash
      
      - name: Setup MacOS Defaults
        run: ./defaults.sh
        shell: bash

      - name: Setup Apps
        run: ./install.sh
        shell: bash